### ISSUE TITLE
Not pulling entire list

### ISSUE THREAD

**Issue by BioCryptTech** [Philipinho/ERC20-Snapshot#2]
When i upload the php and then view it, for some reason it shows me only about 90 wallet addresses. 

For example contract: 0xE50365f5D679CB98a1dd62D6F6e58e59321BcdDf
pages: 439

4382 holders, only seems to be showing about 90

**Comment by Kryptoniq** [comment]
Did you set the `$numpage` parameter to 439?

**Comment by BioCryptTech** [comment]
Yes i have set the numpage to the amoutn of pages shown

**Comment by Kryptoniq** [comment]
Hi @BioCryptTech, from the look of things, ethplorer added a rate limiter to the API endpoint.
However, i was able to get the token holders by making the request to fetch 100 addresses per row. By so doing, i got about 1200 results in each request.
Below are links to the scraped results in 4 pages amounting to 4352 LaToken's token holders.
The VPS instance will be destroyed in about four days. 

http://108.61.188.245/la1.html
http://108.61.188.245/la2.html
http://108.61.188.245/la3.html
http://108.61.188.245/la4.html

**Comment by Kryptoniq** [comment]
Be aware that the balances are in scientific notations, you can convert them to decimal by using excel.
